name: ESP32 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install ESP-IDF dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Set up ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git esp-idf
        cd esp-idf
        ./install.sh
        . ./export.sh

    - name: Build the project
      run: |
        idf.py set-target esp32s3
        idf.py build
