name: ESP32 Arduino-CLI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build_and_validate:
    runs-on: ubuntu-latest # Or your preferred runner OS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        # You can download and install it directly or use a pre-built action if available.
        # This approach downloads and installs it.
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/arduino-cli
          arduino-cli config init

      - name: Add ESP32 Board Manager URL
        run: arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Update Core Indexes
        run: arduino-cli core update-index

      - name: Install ESP32 Board Core
        run: arduino-cli core install esp32:esp32

      - name: Install Libraries (if any)
        # This step is crucial. You need to explicitly list your dependencies.
        # Or, parse them from your sketch if you have many.
        # For simple cases, list them here:
        run: |
          arduino-cli lib install "WiFi"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install --git-url https://github.com/ESP32Async/ESPAsyncWebServer.git
          arduino-cli lib install "Arduino_JSON"

      - name: Arduino-CLI Compile Sketch
        # Replace 'my_sketch' with the actual directory name of your .ino sketch
        # Replace 'esp32:esp32:esp32doit-devkit-v1' with your specific ESP32 board FQBN
        run: arduino-cli compile --fqbn esp32:esp32:esp32s3 . --build-path ./build/esp32.esp32.esp32s3/

      - name: Upload Compiled Binary as Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware-arduino-cli
          path: ./build/esp32.esp32.esp32s3/Flight_controller.ino.bin # Adjust path based on your board and sketch name
          retention-days: 7

  # Optional: Release Job for OTA updates or binary artifacts
  release_firmware:
    needs: build_and_validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Compiled Firmware
        uses: actions/download-artifact@v4
        with:
          name: esp32-firmware-arduino-cli
